title: Allison Bradshaw # your name (or website title) here
logo: "/images/8855CD09-1246-459F-8170-0063A07B9F37_1_201_a.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hi! I'm Allison. 
  <br><br>
  I'm a geographer at heart, and love to use maps to solve complex challenges. Here are a few examples from my professional life.
  <br><br>
  I also like to write about the connection between geography, equity, and resilience. You can find that work over at agbrad.com
  <br><br>
  <a href="https://www.linkedin.com/in/agbrad/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
