title: Allison Bradshaw # your name (or website title) here
logo: "/96A9E880-E4CC-4EC6-B170-107DAD8B4900_1_105_c.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Here is a brief overview of some of my work!
  
  <a href="https://www.linkedin.com/in/agbrad/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
